name: Deploy React App to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Check CSV files in repository
        run: |
          echo "Looking for CSV files in the repository:"
          find . -name "*.csv" -type f
          echo "Contents of public directory:"
          ls -la ./flash-site/public/ || echo "public directory not found"
          if [ -d "./flash-site/public/games" ]; then
            echo "Games directory exists in public:"
            ls -la ./flash-site/public/games/
          fi

      - name: Install dependencies
        run: npm install
        working-directory: ./flash-site

      - name: List package.json scripts (for debugging)
        run: cat package.json | grep -A 10 "scripts"
        working-directory: ./flash-site

      - name: Build
        run: |
          echo "Starting build process..."
          npm run build:prod
          echo "Build completed. Exit code: $?"
        working-directory: ./flash-site

      - name: Verify CSV files after build
        run: |
          echo "Looking for CSV files in build directory:"
          find ./flash-site/build -name "*.csv" -type f
          echo "Contents of build directory:"
          ls -la ./flash-site/build/
          if [ -d "./flash-site/build/games" ]; then
            echo "Games directory exists in build:"
            ls -la ./flash-site/build/games/
          else
            echo "Games directory NOT found in build!"
          fi

      - name: Add 404.html for client-side routing
        run: cp ./flash-site/build/index.html ./flash-site/build/404.html

      - name: Add .nojekyll to disable Jekyll
        run: touch ./flash-site/build/.nojekyll

      - name: Final verification before upload
        run: |
          echo "Final check - CSV files before artifact upload:"
          find ./flash-site/build -name "*.csv" -type f
          echo "Total files in build directory:"
          find ./flash-site/build -type f | wc -l

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./flash-site/build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
